VinayBelwal/Hactober-22-Programs-and-Projects-

MaxmExpression.cpp
Hello @VinayBelwal 
I added a creative analytical question. Can you please merge this request under Hactoberfest2022? Thank you.
=> Added an amazing problem in C++ lang

Trapping_Rain_water_Poblem.cpp
Solution of Trapping rain water problem and below is the link https://leetcode.com/problems/trapping-rain-water/
=> Solution of standard problem of interview

Reversing_String.java
Signed-off-by: Sayak Singha <69098567+Sayak-singha@users.noreply.github.com>
=> Added java solution

Merge_sorted_list.cpp
=> Solution of merge sorted list problem

BST.cpp, avl.cpp, bits.cpp, hackotberfest.cpp
This contain many functions related to dsa  in cpp.
=> Important Topic in DSA problems

Armstrong.cpp
Addedd a new c++ program for finding the numberis armstrong or not .
=> Uploaded Armstrong.cpp

Quick_Sort.cpp, README.md
Added a C++ program performing Quick Sort on the entered array
=> Uploaded Quick_Sort.cpp and Created README.md 

Rat in a maze.cpp
contributed the code of rat in a maze,pls check it and merge.
=> Create Rat in a maze.cpp

Linked_List_Cycle.cpp
Added Added Check for Loop in a Linked List in CPP. It is one of the most popular interview question, this algorithm employs a technique which uses two pointers which move at different speeds through the List in order to detect a loop.
=> Added Check for Loop in a Linked List in CPP

Decode_Ways.cpp
This includes the code for Decoding the no of ways the string can be decoded from ascii numbers. This is a very famous Dynamic Programming question from interviews.
=> Added Decode Ways in CPP

BUBBLE SORT.cpp
code of bubble sort of BEST CASE TIME COMPLEXITY.
PLS ACCEPT MY PULL REQUEST AND PLS ALSO GIVE HACTOBERFEST LABLES
=> Create BUBBLE SORT.cpp

Selection_sort.cpp
Please merge this pull request....
Added Selection Sort in C++
=> Added Selection Sort

shellsort.c
Implemetation of Shell Sort....It will be useful/beneficial for others...Please add my file to your repository with label hacktoberfest.
=> Hacktoberfest-2022

Count_digits.py
Hey, 
If there is anything wrong , let me know
=> Added short trick to count digits

MaxMin_elements.cpp
Please review my code and merge my PR under hactoberfest.
=> Added a cpp program of max and min element.

fibonacci.cpp
=> created fibonacci

Tree_compare.cpp, Tree_max_child_sum.cpp, counting_sort.cpp, print_wise_binary_tree.cpp
Please add my pull request i i have added the program for printing the binary tree level wise
=> Some basic DSA programs 

Fibonacci Search.cpp
- Created new program file.
- easy steps for beginners.
- steps of approach is mentioned by comment tags.
=> Create Fibonacci Search.cpp

Longest Increasing Subsequence.cpp
added the longest increasing subsequency algorithm in CPP to your repository
=>  Hacktoberfest2022

Josephus.cpp, N-Queen.cpp
=> Josephus Problem

Rat-in-a-maze.cpp
Backtrack approach to solve this problem
=> Rat in a maze

Calendar.c
hi @VinayBelwal 
This is Jayadip Sahoo, This is a project on printing calendar of any year In C
please take look at this MR/PR request and approve it with hacktoberfest2022 & hacktoberfest2022-accepted label .
Thanking You
=> Calendar In C

convert decimal to binary.cpp
#include <iostream>
#include <math.h>
using namespace std;
int base10tobase2(int n){
int count=0, ans=0 ,rem ;
while(n!=0){
rem=n%2;
ans+=pow(10,count)*rem;
count++;
n/=2;
}
return ans;
}
int main(){
int n;
cout<<"Enter a decimal number : ";
cin>>n;
cout<<"Binary number of "<<n<<" is "<<base10tobase2(n)<<endl;
return 0;
}
=> Create convert decimal to binary.cpp

Leetcode Problems/Two Sum.py
I have added the Two Sum Leetcode problem in the Leetcode Problems Folder. My Solution is perfectly working correct solution with Time Complexity of O(n). I have used a dictionary to reduce the the time of searching the pairs that add up to Target value because the time complexity of searching a key in a dictionary is O(1).
=> ADDING Two Sum LEETCODE problem into the Leetcode Problems Folder

Leetcode Problems/Reverse Integer.py, Leetcode Problems/Two Sum.py
I would like to add my Reverse integer Leetcode solution to the Leetcode Problems Folder. I have perfect solution to this leetcode problem written in Python Programming language. My code is valid for any inputs within the defined range and works efficiently.
=> Reverse integer

Leetcode Problems/Palindrome Number.py, Leetcode Problems/Reverse Integer.py, Leetcode Problems/Two Sum.py
I would like to add my solution for Palindrome Number Leetcode solution. It is written in python and is perfectly correct solution to the problem. I have written the solution using the most efficient approach without any built-in functions.
=> Palindrome Number LEETCODE SOLUTION

Leetcode Problems/Palindrome Number.py, Leetcode Problems/Remove Duplicates from Sorted Array.py, Leetcode Problems/Reverse Integer.py, Leetcode Problems/Two Sum.py
This is my python solution to the Remove Duplicates from Sorted Array Leetcode Problem. I would like to add my solution to your LEETCODE PROBLEMS. My solution is according to the problem constraints using O(1) extra memory and modifying the array in-place.
=> Remove Duplicates from Sorted Array LEETCODE SOLUTION

Leetcode Problems/Find the Index of the First Occurrence in a String.py, Leetcode Problems/Palindrome Number.py, Leetcode Problems/Remove Duplicates from Sorted Array.py, Leetcode Problems/Reverse Integer.py, Leetcode Problems/Two Sum.py
I would like to share my solution to Find the Index of the First Occurrence in a String LEETCODE Problem. My solution is done in the shortest and most efficient way possible in python.
=> Find the index of the first occurrence in a string

Linked List/Linked List detect_loop.cpp
This program helps to detect loop
=> This program helps to detect loop

cses_countingRooms.cpp
Thank you for reading my pull request. please add my contribution to your repository. link to problem is attached.
https://cses.fi/problemset/task/1192/
=> a new file cses_CountingRooms from cses problemset added

Radix_sort
Easy and understandable algorithm
=> Radix_sort

Zig-Zag Level Order Traversal
Zig-Zag Level Order Traversal cpp solution
Name : Sandhya Mishra
Github id : Sandhyamishra18
=> Zig-Zag Level Order Traversal cpp solution
